#!/bin/sh
case "$1" in
    start)
        { [ -f /boot/REG_UPDATE ] && /usr/sbin/plymouthd --mode=updates --graphical-boot --attach-to-session ; } || /usr/sbin/plymouthd --mode=boot --graphical-boot --attach-to-session
        /usr/bin/plymouth --show-splash
    ;;
    stop)
        # Save the boot log to file and stop splash
        /usr/bin/plymouth update-root-fs --read-write
        /usr/bin/plymouth --wait quit --retain-splash
     ;;
    *)
esac
